specisl_item_rate={
    "维护消耗":1,
    "回收效率":0.2,
    "农场作物产量":1,
    "农场作物需水量":1,
}
buff={
    "edicts":{
        "人口法令":{
            "节省食物":{
                "ID":"edicts-01",
                "icon":"食物消耗减少",
                "intro":"食物消耗减少了?%",
                "effect":[0.2,0.3],
                "unity":[-1,-2]
            },
            "食物充沛":{
                "ID":"edicts-02",
                "icon":"凝聚力产出增加",
                "intro":"食物消耗增加了?%,额外提供凝聚力",
                "effect":[0.2,0.4],
                "unity":[1,2]
            },
            "更多家具用品":{
                "ID":"edicts-03",
                "icon":"凝聚力产出增加",
                "intro":"家具用品消费增加?%，其提供的凝聚力增加",
                "effect":[0.2,0.4,0.7],
                "unity":[0.15,0.3,0.45]
            },
            "更多家电":{
                "ID":"edicts-04",
                "icon":"凝聚力产出增加",
                "intro":"家电消费增加?%，其提供的凝聚力增加",
                "effect":[0.2,0.4,0.7],
                "unity":[0.15,0.3,0.45]
            },
            "更多消费电子产品":{
                "ID":"edicts-05",
                "icon":"凝聚力产出增加",
                "intro":"费电子产品消费增加?%，其提供的凝聚力增加",
                "effect":[0.2,0.4,0.7],
                "unity":[0.15,0.3,0.45]
            }},
        "工业法令":{
            "节省车辆燃料":{
                "ID":"edicts-06",
                "icon":"燃料消耗减少",
                "intro":"车辆燃料消耗减少?%",
                "effect":[0.15,0.25],
                "unity":[-1,-3]
            },
            "节省船舶燃料":{
                "ID":"edicts-07",
                "icon":"燃料消耗减少",
                "intro":"船舶燃料消耗减少?%",
                "effect":[0.15,0.25],
                "unity":[-1,-3]
            },
            "减少维护":{
                "ID":"edicts-08",
                "icon":"维护消耗减少",
                "intro":"维护减少?%",
                "effect":[0.15,0.25,0.3],
                "unity":[-1,-2,-3]
            },
            "增加回收":{
                "ID":"edicts-09",
                "icon":"回收效率增加",
                "intro":"回收效率提高?%",
                "effect":[0.12,0.22,0.3,0.35,0.4],
                "unity":[-1,-2,-3.5,-5,-7]
            },
            "农业提振":{
                "ID":"edicts-10",
                "icon":"农作物产量增加",
                "intro":"农场产量增加?%，需水量增加?%",
                "effect":[0.15,0.27,0.35],
                "unity":[-1,-2,-3]
            },
            "节水器":{
                "ID":"edicts-11",
                "icon":"节水",
                "intro":"将定居点和农场的用水减少?%",
                "effect":[0.15,0.27,0.35],
                "unity":[-1,-2,-3]
            },
            "清洁面板":{
                "ID":"edicts-12",
                "icon":"太阳能发电增加",
                "intro":"将太阳能的输出功率提高?%",
                "effect":[0.05,0.15,0.3],
                "unity":[-0.5,-1.5,-2.5],
            },
            "研究效率":{
                "ID":"edicts-13",
                "icon":"研究效率增加",
                "intro":"研究效率提高?%",
                "effect":[0.15,0.25,0.35,0.45,0.6],
                "unity":[-1,-2,-3,-4,-6],
            }
        }
    },
    "office":{
        "?% 研究效率":{
            "ID":"office-01",
            "icon":"研究效率增加",
            "effect":0.02,
            "focus_by_grade":{
                "a1":25,
                "d":10
            },
            "max_grade":150
        },  
        "?% 维修产量":{
            "ID":"office-02",
            "icon":"维护产出增加",
            "effect":0.01,
            "focus_by_grade":{
                "a1":25,
                "d":10
            },
            "max_grade":100
        },  
        "?% 农作物产量":{
            "ID":"office-03",
            "icon":"农作物产量增加",
            "effect":0.02,
            "focus_by_grade":{
                "a1":50,
                "d":10
            },
            "max_grade":150
        },  
        "?% 回收效率":{
            "ID":"office-04",
            "icon":"回收效率增加",
            "effect":0.01,
            "focus_by_grade":{
                "a1":150,
                "d":50
            },
            "max_grade":15
        },  
        "?% 食物消耗":{
            "ID":"office-05",
            "icon":"食物消耗减少",
            "effect":-0.02,
            "focus_by_grade":{
                "a1":75,
                "d":100
            },
            "max_grade":15
        },  
        "?% 商品与服务消耗":{
            "ID":"office-06",
            "icon":"商品与服务消耗减少",
            "effect":-0.02,
            "focus_by_grade":{
                "a1":125,
                "d":125
            },
            "max_grade":25
        },  
        "?% 来自定居点的凝聚力":{
            "ID":"office-07",
            "icon":"凝聚力产出增加",
            "effect":0.025,
            "focus_by_grade":{
                "a1":250,
                "d":250
            },
            "max_grade":14
        },  
        "?% 合同利润率":{
            "ID":"office-08",
            "icon":"合同利润率增加",
            "effect":0.02,
            "focus_by_grade":{
                "a1":40,
                "d":40
            },
            "max_grade":15
        },  
        "?% 合同凝聚力消耗":{
            "ID":"office-09",
            "icon":"合同凝聚力减少",
            "effect":-0.025,
            "focus_by_grade":{
                "a1":40,
                "d":20
            },
            "max_grade":20
        },  
    },
    "research":{
        "分支1":{
            "作物产量":{
                "ID":"research-01",
                "icon":"农作物产量增加",
                "intro":"?%作物产量.?%作物耗水量",
                "effect":[0.01,0.0025],
                "spaceResearch_need_grade":20,
                "max_grade":250
            },
            "定居点用水":{
                "ID":"research-02",
                "icon":"节水",
                "intro":"?定居点用水量",
                "effect":[-0.02],
                "spaceResearch_need_grade":10,
                "max_grade":40
            },
            "住房容量":{
                "ID":"research-03",
                "icon":"住房 IV",
                "intro":"?%住房容量",
                "effect":[0.05],
                "spaceResearch_need_grade":4,
                "max_grade":40
            },
            "专注点":{
                "ID":"research-04",
                "icon":"专注点",
                "intro":"?%办公室生产的专注点",
                "effect":[0.04],
                "spaceResearch_need_grade":5,
                "max_grade":25
            }
        },
        "分支2":{
            "车辆燃料消耗":{
                "ID":"research-05",
                "icon":"燃料消耗减少",
                "intro":"?%车辆燃料消耗",
                "effect":[-0.01],
                "spaceResearch_need_grade":5,
                "max_grade":35
            },
            "火车燃料消耗":{
                "ID":"research-06",
                "icon":"燃料消耗减少",
                "intro":"?%火车燃料消耗",
                "effect":[-0.01],
                "spaceResearch_need_grade":5,
                "max_grade":35
            },
            "船舰燃料消耗":{
                "ID":"research-07",
                "icon":"燃料消耗减少",
                "intro":"?%船舰燃料消耗",
                "effect":[-0.01],
                "spaceResearch_need_grade":5,
                "max_grade":35
            },
            "火箭载荷量":{
                "ID":"research-08",
                "icon":"火箭 II",
                "intro":"?%火箭有效载荷",
                "effect":[0.05],
                "spaceResearch_need_grade":1,
                "max_grade":20
            },
            "维修产量":{
                "ID":"research-09",
                "icon":"维护产出增加",
                "intro":"?%维修产量",
                "effect":[0.01],
                "spaceResearch_need_grade":4,
                "max_grade":50
            },
            "太阳能发电":{
                "ID":"research-10",
                "icon":"太阳能发电增加",
                "intro":"?%太阳能发电量",
                "effect":[0.02],
                "spaceResearch_need_grade":10,
                "max_grade":200
            }
        }    
    }
}